apiVersion: v1
kind: Service
metadata:
  name: steam-ms-service
spec:
  selector:
    app: steam-ms
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 5000
  type: LoadBalancer
  clusterIP: 10.121.10.165
  loadBalancerIP: 35.239.38.150

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: steam-ms
spec:
  selector:
    matchLabels:
      app: steam-ms
  replicas: 1
  template:
    metadata:
      labels:
        app: steam-ms
    spec:
      containers:
      - name: steam-ms
        image: gcr.io/cc-steam-chat/steam-ms:latest
        ports:
        - containerPort: 5000
        env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: db_user
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: db_password
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: db_name
      - name: cloud-sql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.17
        command:
          - "/cloud_sql_proxy"
          - "-instances=cc-steam-chat:us-central1:steam-chat=tcp:5432"
          - "-credential_file=/secrets/service_account.json"
        securityContext:
          allowPrivilegeEscalation: false
        volumeMounts:
        - name: sql-volume
          mountPath: /secrets/
          readOnly: true
      volumes:
      - name: sql-volume
        secret:
          secretName: sql-secret
