apiVersion: v1
kind: Service
metadata:
  name: steam-ms-service
spec:
  selector:
    app: steam-ms
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 5000
  type: LoadBalancer
  clusterIP: 10.121.10.165
  loadBalancerIP: 35.239.38.150

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: steam-ms
spec:
  selector:
    matchLabels:
      app: steam-ms
  replicas: 1
  template:
    metadata:
      labels:
        app: steam-ms
    spec:
      containers:
      - name: steam-ms
        image: gcr.io/cc-steam-chat/steam-ms:latest
        ports:
        - containerPort: 5000


