apiVersion: v1
kind: Service
metadata:
  name: steam-ms-service
spec:
  selector:
    app: steam-ms
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 5000
  type: LoadBalancer
  clusterIP: 10.121.10.165
  loadBalancerIP: 35.239.38.150

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: steam-ms
spec:
  selector:
    matchLabels:
      app: steam-ms
  replicas: 1
  template:
    metadata:
      labels:
        app: steam-ms
    spec:
      containers:
      - name: steam-ms
        image: gcr.io/cc-steam-chat/steam-ms:latest
        ports:
        - containerPort: 5000
        env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: username
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: database
      - name: cloud-sql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.17
        command:
          - "/cloud_sql_proxy"
          # Replace DB_PORT with the port the proxy should listen on
          # Defaults: MySQL: 3306, Postgres: 5432, SQLServer: 1433
          - "-instances=steam-chat=tcp:5432"
        securityContext:
          # The default Cloud SQL proxy image is based on distroless, which
          # runs as the "nonroot" user (uid: 65534) by default.
          runAsNonRoot: true


